// Code generated by "stringer -type=TypeAST"; DO NOT EDIT.

package walk

import "strconv"

const _TypeAST_name = "PackageFileFuncDeclGenDeclTypeSpecValueSpecImportSpecSpecAllRangeStmtForStmtSelectStmtCommClauseTypeSwitchStmtSwitchStmtCaseClauseIfStmtBlockStmtBranchStmtReturnStmtDeferStmtGoStmtAssignStmtIncDecStmtSendStmtExprStmtLabeledStmtDeclStmtChanTypeMapTypeInterfaceTypeFuncTypeStructTypeArrayTypeTypeAllKeyValueExprBinaryExprUnaryExprStarExprCallExprTypeAssertExprSliceExprIndexExprSelectorExprParenExprCompositeLitFuncLitEllipsisFieldListFieldCommentGroupEmptyStmtBadDeclDeclAllBadStmtStmtAllBasicLitLitAllBadExprExprAllAstAllIdentComment"

var _TypeAST_map = map[TypeAST]string{
	256:                 _TypeAST_name[0:7],
	512:                 _TypeAST_name[7:11],
	1024:                _TypeAST_name[11:19],
	2048:                _TypeAST_name[19:26],
	4096:                _TypeAST_name[26:34],
	8192:                _TypeAST_name[34:43],
	16384:               _TypeAST_name[43:53],
	28672:               _TypeAST_name[53:60],
	32768:               _TypeAST_name[60:69],
	65536:               _TypeAST_name[69:76],
	131072:              _TypeAST_name[76:86],
	262144:              _TypeAST_name[86:96],
	524288:              _TypeAST_name[96:110],
	1048576:             _TypeAST_name[110:120],
	2097152:             _TypeAST_name[120:130],
	4194304:             _TypeAST_name[130:136],
	8388608:             _TypeAST_name[136:145],
	16777216:            _TypeAST_name[145:155],
	33554432:            _TypeAST_name[155:165],
	67108864:            _TypeAST_name[165:174],
	134217728:           _TypeAST_name[174:180],
	268435456:           _TypeAST_name[180:190],
	536870912:           _TypeAST_name[190:200],
	1073741824:          _TypeAST_name[200:208],
	2147483648:          _TypeAST_name[208:216],
	4294967296:          _TypeAST_name[216:227],
	8589934592:          _TypeAST_name[227:235],
	17179869184:         _TypeAST_name[235:243],
	34359738368:         _TypeAST_name[243:250],
	68719476736:         _TypeAST_name[250:263],
	137438953472:        _TypeAST_name[263:271],
	274877906944:        _TypeAST_name[271:281],
	549755813888:        _TypeAST_name[281:290],
	1082331758592:       _TypeAST_name[290:297],
	1099511627776:       _TypeAST_name[297:309],
	2199023255552:       _TypeAST_name[309:319],
	4398046511104:       _TypeAST_name[319:328],
	8796093022208:       _TypeAST_name[328:336],
	17592186044416:      _TypeAST_name[336:344],
	35184372088832:      _TypeAST_name[344:358],
	70368744177664:      _TypeAST_name[358:367],
	140737488355328:     _TypeAST_name[367:376],
	281474976710656:     _TypeAST_name[376:388],
	562949953421312:     _TypeAST_name[388:397],
	1125899906842624:    _TypeAST_name[397:409],
	2251799813685248:    _TypeAST_name[409:416],
	4503599627370496:    _TypeAST_name[416:424],
	9007199254740992:    _TypeAST_name[424:433],
	18014398509481984:   _TypeAST_name[433:438],
	36028797018963968:   _TypeAST_name[438:450],
	72057594037927936:   _TypeAST_name[450:459],
	144115188075855872:  _TypeAST_name[459:466],
	144115188075858944:  _TypeAST_name[466:473],
	288230376151711744:  _TypeAST_name[473:480],
	360287987369476096:  _TypeAST_name[480:487],
	576460752303423488:  _TypeAST_name[487:495],
	593349250906062848:  _TypeAST_name[495:501],
	1152921504606846976: _TypeAST_name[501:508],
	1154046305002061824: _TypeAST_name[508:515],
	2305843009213693696: _TypeAST_name[515:521],
	2305843009213693952: _TypeAST_name[521:526],
	4611686018427387904: _TypeAST_name[526:533],
}

func (i TypeAST) String() string {
	if str, ok := _TypeAST_map[i]; ok {
		return str
	}
	return "TypeAST(" + strconv.FormatInt(int64(i), 10) + ")"
}
